version: '3.8'
services:
  models-stable-diffusion-xl-light:
    build: ./microservices/stable-diffusion
    volumes:
      - ~/.cache/huggingface/:/root/.cache/huggingface/
      - ~/.cache/pip/:/root/.cache/pip/
    image: yenicelik/models-stable-diffusion-xl-light:v0.1
    ports:
      - 8080:8080
  # uvicorn --port 8080 --backlog 5 --timeout-keep-alive 500 --workers 1 main:app
  # gradio-frontend:
  #   build: ./simple-frontend
  #   environment:
  #     - API_STABLEDIFFUSION=http://localhost:2500/predict
  #   entrypoint: python -m main
  #   ports:
  #     - 2503:2503
